development:
  adapter: postgresql
  encoding: unicode
  database: ember_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ember_test
  pool: 5
  host: localhost
